### ISSUE TITLE
Integrate Fortmatic as alternative onboarding provider

### ISSUE THREAD

**Issue by faridrached** [Alexintosh/PIE-landing#117]
Fortmatic is an easy tool that allows users to get onboarded easily on any major browser on both mobile and desktop. No extra downloads/extensions or remembering seedphrases necessary anymore. 

- Select a type of issue
-->
- [x] Enhancement
- [ ] Maintenance
- [ ] Refactor

On https://fortmatic.com/ head to 'Get Started', sign in and follow the steps to integrate Fortmatic. 

 Definition of Done

- when clicking on 'connect Web3' it should provide the option to sign in with both Metamask (current) and Fortmatic. Ideally Fortmatic framed as 'login with email or phonenumber'
- Signing transactions with Fortmatic should work properly

**Comment by Alexintosh** [comment]
Would be nice to see a PR as well!
