### ISSUE TITLE
Dynamic Newsletter Counter

### ISSUE THREAD

**Issue by dimarconicola** [Alexintosh/PIE-landing#20]
#### User Story
As a user, I want to see the spots left in order to join the beta testing program
As an admin, I want to create urgency for the users in order to incentivize them to subscribe to the beta 

#### Type
- [ ] Enhancement

#### Description
At the moment, on the subscribe form, the number showed is static but it needs to be dynamic so that, when the user subscribes, it will change accordingly

#### Solution
Connect the component to Mailchimp.
The subscribe form has a hidden checkbox (checked by default and named PIE) that we use to differentiate the source audience on Mailchimp.
Use Mailchimp API to identify the current number of subscribers and dynamically update the number on the counter placed underneath the subscription form.

#### Attach files or screenshots if it's helpful for this issue.
<img width="490" alt="Screenshot 2020-01-08 at 09 47 12" src="https://user-images.githubusercontent.com/10923247/71987279-e793d900-31fb-11ea-96ee-46d220728f6e.png">

**Comment by Alexintosh** [comment]
This should help @dimarconicola @dmvt 
https://gist.github.com/kovshenin/18892578342132f88b8b

**Comment by MickdeGraaf** [comment]
Do we still need this? Considering we are going less public before launch
