### ISSUE TITLE
WIP Bug list

### ISSUE THREAD

**Issue by dimarconicola** [Alexintosh/PIE-landing#54]
**BUGS**
- [x] swap containers on mobile for Mint-Redeem (the slider should go on top)
- [x] Portfolio pages is not responsive (mobile)
- [x]  Mint-Redeem page is not responsive (mobile)
- [x] BUY Modal is not responsive (mobile)
- [x] Hero names do not visualize correctly on certain screen sizes (see screenshot)
- [x] Logo does not respect aspect ratio when scaling down the screen

- [ ] Token names should be the correct one (i.e. sTLT not TLT)
- [x] the mobile menu hamburger icon does not appear for screens smaller than 340px
- [x] "Get early access" button on the homepage has currently no action
- [x] Select web3 provider appears on mobile web3 browser but it shows only Metamask hence it's currently impossible to use it from mobile web3 browsers, not even from Metamask mobile
- [x] In the BUY modal, if I input a number, I delete it, the output and other info underneath are not going back to default. Also once I delete the number I typed, the input goes back to zero but it also goes automatically out of focus.
- [ ] There's some problem with routing as it says "page not found" (see screenshot)
- [ ] If I connect on Kovan but then I switch to Mainnet the button on the BUY modal should be greyed out or show an appropriate message (right now it only says "BUY").
- [ ] All the numbers in the portfolio page are wired. Tot value both on the chart and the recap is off. So are gains.
- [x] we should either connect the counter to Mailchimp or get rid of the counter altogether 
- [ ] redeem() fail (worked with not max amount and higher gasLimit)
- [x] redeemRebalancingSet() 1.2M gas units
- [ ] Mint starts a popup for "Approve()" the contract but after that approval, never ask for the execution of the actual action, and no CTA in the UI
- [ ] 

**IMPROVEMENTS**
- [x] In Add-Remove the single asset item should have a fixed width because right now it changes it once the user interacts with the slider
- [x] Add Liquidity / Remove Liquidity items on the tab navigation should have a pointer cursor
- [x] FAQ should show a pointer cursor on mouse over
- [x] 2018 returns on the comparison table should have a $ label
- [x] AWP icon should be different than AWP++ on the comparison table (maybe without glasses?)
- [x] Portfolio/Your-Investment: we should show AWP++ Amount, add a $ label to Gains
- [x] Big screens container for all components (especially transaction list, comparison table, the whole mint-redeem page)
- [x] Restore rotating HERO and introduce more breakpoints
- [x] Reduce label text size on the charts
- [x] etherscan link on the transaction list needs some styling
- [x] Do we want to add Etherscan link for transactions?
- [x] Mixpanel tracking
- [x] The chart in portfolio needs some styling, labels are too big and date format is too long
- [ ] date format is GMT by default but it would be nice to change it according to location
- [ ] Would be nice if the modal appears with a smooth transition
- [ ] Disclaimer (by connecting the wallet you will accept terms and conditions...)
- [ ] In Add-Remove liquidity, colors for the underlying asset labels are redundant. We need to add more
- [ ] We should show a portfolio breakdown also on the portfolio page
- [ ] Error modal needs some styling (see screenshot)
- [ ] Mint-Redeem transactions should be included in the transactions list
- [ ] Make the amount on the Mint-Redeem an input as the slider is not sufficient for this interaction
- [ ] Show a flag to "add to a Uniswap market" for the Mint-Redeem
- [ ] Add small buttons for approvals on Mint-Redeem
- [ ] totalPositionValue label should have separate words
- [ ] There should be a loader while waiting for the data after the first buy (or at least a placeholder)
- [ ] Do we need cookies, privacy policy, disclaimers and in general a footer?
- [ ] Once added or removed liquidity the page should update and the slider should go do default (zero)
- [ ] When Add-Remove liquidity, can we change Metamask Message (sUSB20, see screenshot)?

**EXTRA**
- [ ] styles are redundant

<img width="1280" alt="Screenshot 2020-02-03 at 11 17 42" src="https://user-images.githubusercontent.com/10923247/73670262-e9c04a80-4676-11ea-8fcd-831108078555.png">

<img width="642" alt="Screenshot 2020-02-03 at 11 22 47" src="https://user-images.githubusercontent.com/10923247/73670628-93074080-4677-11ea-93d8-bbcf4b529d46.png">

<img width="372" alt="Screenshot 2020-02-03 at 12 02 01" src="https://user-images.githubusercontent.com/10923247/73673709-2131f580-467d-11ea-962d-3e7d52b79b0a.png">

<img width="860" alt="Screenshot 2020-02-03 at 12 13 41" src="https://user-images.githubusercontent.com/10923247/73674553-c1d4e500-467e-11ea-836f-e9e8cabe242e.png">

**Comment by MickdeGraaf** [comment]
redeemRebalancingSet() gas usage is not a bug. Its costly to redeem set tokens. If we opt for balancer it will be much more efficient.
