### ISSUE TITLE
Images are not displayed correctly in Macbook 13

### ISSUE THREAD

**Issue by Alexintosh** [Alexintosh/PIE-landing#6]
<img width="1434" alt="Screen Shot 2019-12-24 at 12 19 32 PM" src="https://user-images.githubusercontent.com/776519/71410965-b89c3580-2647-11ea-97f1-7dbd0ddafd85.png">
<img width="1438" alt="Screen Shot 2019-12-24 at 12 19 28 PM" src="https://user-images.githubusercontent.com/776519/71410968-b89c3580-2647-11ea-95d6-1dead6099a4d.png">

**Comment by dimarconicola** [comment]
@Alexintosh can you please check again?
