### ISSUE TITLE
Impossible to connectweb3 from mobile browsers

### ISSUE THREAD

**Issue by dimarconicola** [Alexintosh/PIE-landing#63]
#### Priority + Rationale

As a user, I want o to be able to connect web3 also when visiting the website from a mobile web3 browser

#### Describe the bug

When trying to connect to web3, a modal shows up with only Metamask as an option.
If I click on the Metamast button it shows an error.

#### Steps to Reproduce

- From TrustWallet browser
- Go to piedao.org
- Click on the connectweb3 button on the top navi
- Click on Connect Metamask
- Here's the error message

#### Relevant screenshots

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**

Both iOS and Android, on Trust Wallet

**Comment by MickdeGraaf** [comment]
Afaik Trust Wallet has no support for Kovan. I get a wrong network error when trying to connect.

I'm testing with Metamask mobile now which does have issues connecting.

**Comment by dimarconicola** [comment]
@MickdeGraaf  Can we handle a better error message when the user is on the wrong network?
The following screenshot is Trustwallet.
![IMG_CA33B96D098D-1](https://user-images.githubusercontent.com/10923247/74448063-5510d600-4e48-11ea-91bb-24c98061493d.jpeg)

This is instead Metamask (in kovan)
![IMG_34089F46A271-1](https://user-images.githubusercontent.com/10923247/74448148-78d41c00-4e48-11ea-8a3f-107e24da4d9a.jpeg)
